version: '2'
services:
  node:
    build: node
    restart: always
    volumes:
      - ./node_data:/usr/src/app/chaindata
  web:
    build: web
    restart: always
    depends_on:
      - node
    ports:
      - "4001:8000"
    volumes:
      - ./storage:/storage
      - ./node_data:/node_data
